[project]
name = "data-access-control-contracts"
authors = []
description = ""
telemetry = true

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[project.cache_location]
path = ".requirements"

[contracts.rolesAccess]
path = "contracts/rolesAccess.clar"

[contracts.tokenAccess]
path = "contracts/tokenAccess.clar"

[contracts.accessNFT]
path = "contracts/accessNFT.clar"

[contracts.ownershipNFT]
path = "contracts/ownershipNFT.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
